const productDetailsData = {
    "amazon": {
        "cena": "95,00 €",
        "velkost": "130 cm x 301 cm (3,91m²)",
        "hrubka": "~ 10 – 20 mm",
        "hlbka": "~ 20 – 22 mm",
        "hmotnost": "~ 8 – 9 kg / m²",
        "hustota": "1,46 gr / cm³",
        "nehorlavost": "Trieda A2",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 dB",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "baobab": {
        "cena": "95,00 €",
        "velkost": "300 x 130cm (3,90m²)",
        "hrubka": "~ 15 – 25 mm",
        "hlbka": "~ 25 – 30 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "boltz": {
        "cena": "105,00 €",
        "velkost": "259 cm x 129 cm (3,34m²)",
        "hrubka": "~ 9 – 11 mm",
        "hlbka": "~ 11 – 13 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "broderie": {
        "cena": "100,00 €",
        "velkost": "247 cm x 124 cm (3,06m²)",
        "hrubka": "~ 10 – 12 mm",
        "hlbka": "~ 10 – 12 mm",
        "hmotnost": "~ 6 – 7 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "epicure": {
        "cena": "100,00 €",
        "velkost": "241 cm x 120 cm (2,89m²)",
        "hrubka": "~ 10 – 13 mm",
        "hlbka": "~ 10 – 13 mm",
        "hmotnost": "~ 6 – 7 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "forg": {
        "cena": "105,00 €",
        "velkost": "259 cm x 128 cm (3,31m²)",
        "hrubka": "~ 15 – 17 mm",
        "hlbka": "~ 18 – 20 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "g-qube": {
        "cena": "105,00 €",
        "velkost": "259 x 129cm (3,34m²)",
        "hrubka": "~ 16 – 20 mm",
        "hlbka": "~ 16 – 20 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "grenier": {
        "cena": "100,00 €",
        "velkost": "246 x 122cm (3,00m²)",
        "hrubka": "~ 10 – 12 mm",
        "hlbka": "~ 12 – 16 mm",
        "hmotnost": "~ 6 – 7 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "heritage": {
        "cena": "105,00 €",
        "velkost": "301 x 118cm (3,55m²)",
        "hrubka": "~ 14 – 20 mm",
        "hlbka": "~ 20 – 24 mm",
        "hmotnost": "~ 9 – 10 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "hormigon": {
        "cena": "83,00 €",
        "velkost": "300 cm x 133 cm (3,99m²)",
        "hrubka": "~ 8 – 10 mm",
        "hlbka": "~ 18 – 22 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "hormigon loft": {
        "cena": "83,00 €",
        "velkost": "298 cm x 127 cm (3,78m²)",
        "hrubka": "~ 10 – 15 mm",
        "hlbka": "~ 10 – 15 mm",
        "hmotnost": "~ 6 – 7 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "hormigon plus oxido": {
        "cena": "95,00 €",
        "velkost": "299 x 134 cm (4,00 m²)",
        "hrubka": "~ 10 – 14 mm",
        "hlbka": "~ 10 – 14 mm",
        "hmotnost": "~ 6 – 7 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "hormigon vintage": {
        "cena": "95,00 €",
        "velkost": "296 x 126cm (3,72m²)",
        "hrubka": "~ 12 – 20 mm",
        "hlbka": "~ 20 – 30 mm",
        "hmotnost": "~ 8 – 9 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "horming plus": {
        "cena": "83,00 €",
        "velkost": "299 x 134 cm (4,00 m²)",
        "hrubka": "~ 10 – 12 mm",
        "hlbka": "~ 25 – 30 mm",
        "hmotnost": "~ 6 – 7 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "jakarta": {
        "cena": "95,00 €",
        "velkost": "238 cm x 120 cm (2,85m²)",
        "hrubka": "~ 12 – 14 mm",
        "hlbka": "~ 14 – 16 mm",
        "hmotnost": "~ 8 – 9 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "kors": {
        "cena": "95,00 €",
        "velkost": "278 cm x 117 cm (3,25m²)",
        "hrubka": "~ 12 – 14 mm",
        "hlbka": "~ 14 – 16 mm",
        "hmotnost": "~ 8 – 9 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "ladrillo": {
        "cena": "83,00 €",
        "velkost": "294 cm x 130 cm (3,82m²)",
        "hrubka": "~ 12 – 14 mm",
        "hlbka": "~ 15 – 20 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "ladrillo loft": {
        "cena": "95,00 €",
        "velkost": "305 x 129cm (3,93m²)",
        "hrubka": "~ 15 – 20 mm",
        "hlbka": "~ 20 – 22 mm",
        "hmotnost": "~ 10 – 11 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "ladrillo preforado": {
        "cena": "95,00 €",
        "velkost": "299 cm x 129 cm (3,85m²)",
        "hrubka": "~ 12 – 16 mm",
        "hlbka": "~ 16 – 20 mm",
        "hmotnost": "~ 8 – 9 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "ladrillo vintage": {
        "cena": "70,00 €",
        "velkost": "298 x 127cm (3,78m²)",
        "hrubka": "~ 12 – 14 mm",
        "hlbka": "~ 15 – 20 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "lajas": {
        "cena": "83,00 €",
        "velkost": "302 x 131cm (3,95m²)",
        "hrubka": "~ 12 – 16 mm",
        "hlbka": "~ 14 – 18 mm",
        "hmotnost": "~ 9 – 10 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "lastra": {
        "cena": "83,00 €",
        "velkost": "298 cm x 131 cm (3,90m²)",
        "hrubka": "~ 12 – 20 mm",
        "hlbka": "~ 14 – 20 mm",
        "hmotnost": "~ 9 – 10 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "magma": {
        "cena": "95,00 €",
        "velkost": "397 x 130 cm (3,86 m²)",
        "hrubka": "~ 10 – 12 mm",
        "hlbka": "~ 25 – 30 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "mayon cobriza": {
        "cena": "105,00 €",
        "velkost": "132x115cm (1,51m²)",
        "hrubka": "~ 30 – 40 mm",
        "hlbka": "~ 40 – 45 mm",
        "hmotnost": "~ 11 – 13 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "picada": {
        "cena": "83,00 €",
        "velkost": "301 cm x 131 cm (3,94m²)",
        "hrubka": "~ 12 – 14 mm",
        "hlbka": "~ 12 – 14 mm",
        "hmotnost": "~ 6 – 7 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "pizzara": {
        "cena": "89,00 €",
        "velkost": "301 x 137 cm (4,12 m²)",
        "hrubka": "~ 12 – 18 mm",
        "hlbka": "~ 22 – 25 mm",
        "hmotnost": "~ 8 – 9 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "Bez praskania",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "plafont": {
        "cena": "100,00 €",
        "velkost": "246 cm x 123 cm (3,02m²)",
        "hrubka": "~ 16 – 18 mm",
        "hlbka": "~ 16 – 18 mm",
        "hmotnost": "~ 6 – 7 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "roca": {
        "cena": "95,00 €",
        "velkost": "299 x 131 cm (3,91 m²)",
        "hrubka": "~ 15 – 20 mm",
        "hlbka": "~ 40 – 60 mm",
        "hmotnost": "~ 8 – 9 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "rootz": {
        "cena": "105,00 €",
        "velkost": "259 cm x 129 cm (3,30m²)",
        "hrubka": "~ 16 – 18 mm",
        "hlbka": "~ 24 – 26 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "ruina": {
        "cena": "95,00 €",
        "velkost": "296 x 127 cm (3,75 m²)",
        "hrubka": "~ 10 mm – 20 mm",
        "hlbka": "~ 20 mm – 30 mm",
        "hmotnost": "~ 9 – 10 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "rustica": {
        "cena": "95,00 €",
        "velkost": "298 cm x 132 cm (3,93m²)",
        "hrubka": "~ 15 – 25 mm",
        "hlbka": "~ 25 – 35 mm",
        "hmotnost": "~ 9 – 10 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "sillarejo": {
        "cena": "95,00 €",
        "velkost": "300 x 130cm (3,90m²)",
        "hrubka": "~ 15 – 25 mm",
        "hlbka": "~ 25 – 35 mm",
        "hmotnost": "~ 9 – 10 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "timber": {
        "cena": "95,00 €",
        "velkost": "281x109cm (3,90m²)",
        "hrubka": "~ 10 – 14 mm",
        "hlbka": "~ 20 – 25 mm",
        "hmotnost": "~ 9 – 10 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "tocho": {
        "cena": "95,00 €",
        "velkost": "299 x 132 cm (3,94 m²)",
        "hrubka": "~ 10 – 25 mm",
        "hlbka": "~ 25 – 35 mm",
        "hmotnost": "~ 10 – 11 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "vermont": {
        "cena": "100,00 €",
        "velkost": "242 x 121cm (2,92m²)",
        "hrubka": "~ 10 – 20 mm",
        "hlbka": "~ 12 – 20 mm",
        "hmotnost": "~ 8 – 9 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "versailles": {
        "cena": "100,00 €",
        "velkost": "244 x 123cm (3,00m²)",
        "hrubka": "~ 10 – 12 mm",
        "hlbka": "~ 10 – 12 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "victorian": {
        "cena": "100,00 €",
        "velkost": "247 x 124cm (3,06m²)",
        "hrubka": "~ 10 – 16 mm",
        "hlbka": "~ 12 – 18 mm",
        "hmotnost": "~ 7 – 8 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "wood barbados": {
        "cena": "95,00 €",
        "velkost": "297 cm x 130 cm (3,86m²)",
        "hrubka": "~ 10 – 40 mm",
        "hlbka": "~ 25 – 40 mm",
        "hmotnost": "~ 9 – 10 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "woxx": {
        "cena": "105,00 €",
        "velkost": "258 cm x 128 cm (3,30m²)",
        "hrubka": "~ 12 – 14 mm",
        "hlbka": "~ 14 – 20 mm",
        "hmotnost": "~ 9 – 10 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    },
    "zanzibar": {
        "cena": "83,00 €",
        "velkost": "300 x 130 cm (3,90 m²)",
        "hrubka": "~ 10 – 20 mm",
        "hlbka": "~ 25 – 35 mm",
        "hmotnost": "~ 8 – 9 kg / m²",
        "zaruka": "15 rokov (interiér) // 10 rokov (exteriér)",
        "nehorlavost": "Trieda A2",
        "hustota": "1,46 gr / cm³",
        "teplota": "Žiadne zhoršenie pri 800 °C",
        "tvrdost": "52 (Barcol)",
        "naraz_gulova": "Žiadne praskliny",
        "naraz_charpy": "30 kj / m²",
        "zvuk": "40 dB",
        "mraz": "Bez poškodenia"
    }
};
